### ISSUE TITLE
Git master doesn't build on Ubuntu 19.04

### ISSUE THREAD

**Issue by prokoudine** [vgc/vgc#144]
Hello! Unsure if you accept bug reports for builds from git master, but hey... Gotta try it :)

```
alex@carbon:~/soft/graphics/vgc/vgc-2019-08-24/build$ cmake ..
-- Found Qt 5.12.2: /usr/lib
-- pybind11 v2.2.1
-- VGC Library: core
-- VGC Library: core (python wrappers)
-- VGC Library: core (tests)
-- VGC Library: dom
-- VGC Library: dom (python wrappers)
-- VGC Library: dom (tests)
-- VGC Library: geometry
-- VGC Library: geometry (python wrappers)
-- VGC Library: opengl
-- VGC Library: scene
-- VGC Library: widgets
-- VGC App: illustration
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alex/soft/graphics/vgc/vgc-2019-08-24/build
alex@carbon:~/soft/graphics/vgc/vgc-2019-08-24/build$ LC_ALL=en_US make
Traceback (most recent call last):
  File "/home/alex/soft/graphics/vgc/vgc-2019-08-24/tools/version.py", line 192, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone
make[2]: *** [CMakeFiles/version.dir/build.make:57: CMakeFiles/version] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/version.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

```

I don't think the README mentions anything like that. What deps other than python3-dev and essential build stuff do I need to install?

**Comment by dalboris** [comment]
Of course I accept bug requests :) This definitely sounds like you have a version of python too old, maybe cmake is picking up Python 2 instead of Python 3. Can you try adding `-DPYTHON_EXECUTABLE=</path/to/python3>` to your initial `cmake` call?

**Comment by dalboris** [comment]
(Note: even if you resolve this, don't close it yet, I should enforce Python 3.6+ in the CMakeLists file so that the error message would be clearer)

**Comment by dalboris** [comment]
I have this working on Ubuntu 18.04, with Qt installed to "~/Qt/5.12.4" :

```
$ git clone https://github.com/vgc/vgc.git
$ mkdir build-vgc
$ cd build-vgc
$ cmake ../vgc -DQt="~/Qt/5.12.4/gcc_64" -DPYTHON_EXECUTABLE="/usr/bin/python3"
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") 
-- Found Qt 5.12.4: /home/boris/Qt/5.12.4/gcc_64
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- pybind11 v2.2.1
-- VGC Library: core
-- VGC Library: core (python wrappers)
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- VGC Library: core (tests)
-- VGC Library: dom
-- VGC Library: dom (python wrappers)
-- VGC Library: dom (tests)
-- VGC Library: geometry
-- VGC Library: geometry (python wrappers)
-- VGC Library: opengl
You have called ADD_LIBRARY for library vgc_lib_opengl without any source files. This typically indicates a problem with your CMakeLists.txt file
-- VGC Library: scene
-- VGC Library: widgets
-- VGC App: illustration
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/boris/Documents/vgctrees/build-4
```

If this still fails for you, make sure to try on a brand new `build` folder (because CMake caches stuff), and look for the two lines:

```
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") 
```

These should indicate Python 3.6+.

**Comment by dalboris** [comment]
Alright, with the latest commit, you shouldn't even have to add `-DPYTHON_EXECUTABLE="/usr/bin/python3"` to your cmake call. CMake should now be smart enough to pick up Python 3 if you have both Python 2 and Python 3.

I believe this should work on a fresh Ubuntu 19.04:

1. `sudo apt-get install git cmake build-essential python3-dev libgl1-mesa-dev`
2. Install Qt 5.12.4 to `~/Qt/5.12.4` using the installer downloadable at https://qt.io
3. 
```
$ git clone https://github.com/vgc/vgc.git
$ mkdir build-vgc
$ cd build-vgc
$ cmake ../vgc -DQt="~/Qt/5.12.4/gcc_64"
$ make
$ bin/vgcillustration
```

**Comment by prokoudine** [comment]
Pulled changes, tried it with my system-wide Qt 5.12.2 installation:

```
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.8") 
CMake Error at third/pybind11/tools/FindPythonLibsNew.cmake:95 (message):
  Python config failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig'

  Error in sys.excepthook:

  Traceback (most recent call last):

    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
      from apport.fileutils import likely_packaged, get_recent_crashes
    File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
      from apport.report import Report
    File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
      import apport.fileutils
    File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
      from apport.packaging_impl import impl as packaging
    File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
      import apt
    File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
      import apt_pkg

  ModuleNotFoundError: No module named 'apt_pkg'

  

  Original exception was:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig'

Call Stack (most recent call first):
  third/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  third/pybind11/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/home/alex/soft/graphics/vgc/vgc-2019-08-25/build/CMakeFiles/CMakeOutput.log".
```

**Comment by prokoudine** [comment]
I do have python3-apt installed though.

**Comment by dalboris** [comment]
H

**Comment by dalboris** [comment]
(missed-clicked the close button sorry)

Hum, that is really weird, it sounds completely unrelated to vgc, I'm not using this `apt` module. Have you tried deleting your `build` folder and try again from scratch? (potential caching issue).

I'll look around see if other people on the net have the same problem.

**Comment by prokoudine** [comment]
Yeah, I tried from scratch too. Same error.

**Comment by dalboris** [comment]
Ok, so it definitely sounds like there is some problem with your installation of Python, with different versions conflicting with one another. The following answer seems to nicely explain what could be the problem and the solution:

https://stackoverflow.com/a/53153996/1951907

1. Do you remember exactly which different versions of pythons you have installed, and how?

2. Could you let me know the output of:

```
ls -al /usr/bin | grep python
ls -al /usr/lib | grep python
ls -al /usr/lib/python3/dist-packages/ | grep apt_pkg
```

3. Could you try the following:

```
cd /usr/lib/python3/dist-packages/
sudo ln -s apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so
```

Then try again to compile VGC.

**Comment by prokoudine** [comment]
Unfortunately, I get the same error.

**Comment by dalboris** [comment]
Can you copy-paste here the output of these commands?

```
ls -al /usr/bin | grep python
ls -al /usr/lib | grep python
ls -al /usr/lib/python3/dist-packages/ | grep apt_pkg
```

Then copy-paste the entirety of your cmake command and output from a clean build folder?

Thanks!

**Comment by prokoudine** [comment]
```
$ ls -al /usr/bin | grep python
lrwxrwxrwx  1 root root          26 мар  8 10:23 dh_pypy -> ../share/dh-python/dh_pypy
-rwxr-xr-x  1 root root        1056 мар  4 18:48 dh_python2
lrwxrwxrwx  1 root root          29 мар  8 10:23 dh_python3 -> ../share/dh-python/dh_python3
lrwxrwxrwx  1 root root          23 апр  6 04:42 pdb2.7 -> ../lib/python2.7/pdb.py
lrwxrwxrwx  1 root root          23 апр  9 07:59 pdb3.6 -> ../lib/python3.6/pdb.py
lrwxrwxrwx  1 root root          23 апр  3 08:39 pdb3.7 -> ../lib/python3.7/pdb.py
lrwxrwxrwx  1 root root          31 мар 26 13:25 py3versions -> ../share/python3/py3versions.py
-rwxr-xr-x  1 root root         378 авг 28  2018 pybabel-python2
lrwxrwxrwx  1 root root          26 мар  8 10:23 pybuild -> ../share/dh-python/pybuild
lrwxrwxrwx  1 root root           7 мар  4 18:48 python -> python2
lrwxrwxrwx  1 root root           9 мар  4 18:48 python2 -> python2.7
-rwxr-xr-x  1 root root     3691008 апр  6 04:42 python2.7
lrwxrwxrwx  1 root root          33 апр  6 04:42 python2.7-config -> x86_64-linux-gnu-python2.7-config
lrwxrwxrwx  1 root root          16 мар  4 18:48 python2-config -> python2.7-config
-rwxr-xr-x  1 root root         154 дек  4  2018 python2-pbr
lrwxrwxrwx  1 root root           9 мар 26 13:25 python3 -> python3.7
-rwxr-xr-x  2 root root     4530552 апр  9 07:59 python3.6
lrwxrwxrwx  1 root root          33 апр  9 07:59 python3.6-config -> x86_64-linux-gnu-python3.6-config
-rwxr-xr-x  2 root root     4530552 апр  9 07:59 python3.6m
lrwxrwxrwx  1 root root          34 апр  9 07:59 python3.6m-config -> x86_64-linux-gnu-python3.6m-config
-rwxr-xr-x  2 root root     4877888 апр  3 08:39 python3.7
lrwxrwxrwx  1 root root          33 апр  3 08:39 python3.7-config -> x86_64-linux-gnu-python3.7-config
-rwxr-xr-x  1 root root         407 янв 25  2019 python3.7-coverage
-rwxr-xr-x  2 root root     4877888 апр  3 08:39 python3.7m
lrwxrwxrwx  1 root root          34 апр  3 08:39 python3.7m-config -> x86_64-linux-gnu-python3.7m-config
lrwxrwxrwx  1 root root          16 мар 26 13:25 python3-config -> python3.7-config
-rwxr-xr-x  1 root root         403 янв 25  2019 python3-coverage
lrwxrwxrwx  1 root root          10 мар 26 13:25 python3m -> python3.7m
lrwxrwxrwx  1 root root          17 мар 26 13:25 python3m-config -> python3.7m-config
-rwxr-xr-x  1 root root         152 дек  4  2018 python3-pbr
lrwxrwxrwx  1 root root          14 мар  4 18:48 python-config -> python2-config
lrwxrwxrwx  1 root root          29 мар  4 18:48 pyversions -> ../share/python/pyversions.py
-rwxr-xr-x  1 root root        2971 апр  6 04:42 x86_64-linux-gnu-python2.7-config
lrwxrwxrwx  1 root root          33 мар  4 18:48 x86_64-linux-gnu-python2-config -> x86_64-linux-gnu-python2.7-config
lrwxrwxrwx  1 root root          34 апр  9 07:59 x86_64-linux-gnu-python3.6-config -> x86_64-linux-gnu-python3.6m-config
-rwxr-xr-x  1 root root        3283 апр  9 07:59 x86_64-linux-gnu-python3.6m-config
lrwxrwxrwx  1 root root          34 апр  3 08:39 x86_64-linux-gnu-python3.7-config -> x86_64-linux-gnu-python3.7m-config
-rwxr-xr-x  1 root root        3291 апр  3 08:39 x86_64-linux-gnu-python3.7m-config
lrwxrwxrwx  1 root root          33 мар 26 13:25 x86_64-linux-gnu-python3-config -> x86_64-linux-gnu-python3.7-config
lrwxrwxrwx  1 root root          34 мар 26 13:25 x86_64-linux-gnu-python3m-config -> x86_64-linux-gnu-python3.7m-config
lrwxrwxrwx  1 root root          31 мар  4 18:48 x86_64-linux-gnu-python-config -> x86_64-linux-gnu-python2-config
$ ls -al /usr/lib | grep python
lrwxrwxrwx   1 root root       32 ноя 23  2017 libpyglib-2.0-python2.7.so -> libpyglib-2.0-python2.7.so.0.0.0
drwxr-xr-x  27 root root    24576 июн  6 18:18 python2.7
drwxr-xr-x   3 root root     4096 окт 18  2018 python3
drwxr-xr-x  29 root root    20480 июн  5 15:00 python3.6
drwxr-xr-x  30 root root    20480 июн  5 14:55 python3.7
drwxr-xr-x   5 root root     4096 июн  5 14:51 python3.8
$ ls -al /usr/lib/python3/dist-packages/ | grep apt_pkg
-rw-r--r--   1 root root 355072 мар 11 14:49 apt_pkg.cpython-37m-x86_64-linux-gnu.so
-rw-r--r--   1 root root   9740 мар 11 14:49 apt_pkg.pyi
lrwxrwxrwx   1 root root     39 авг 25 14:16 apt_pkg.so -> apt_pkg.cpython-36m-x86_64-linux-gnu.so
$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3.6 (found suitable version "3.6.8", minimum required is "3.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.8", minimum required is "3.6") 
-- Found Qt 5.12.2: /usr/lib
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.8") 
CMake Error at third/pybind11/tools/FindPythonLibsNew.cmake:95 (message):
  Python config failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig'

  Error in sys.excepthook:

  Traceback (most recent call last):

    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
      from apport.fileutils import likely_packaged, get_recent_crashes
    File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
      from apport.report import Report
    File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
      import apport.fileutils
    File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
      from apport.packaging_impl import impl as packaging
    File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
      import apt
    File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
      import apt_pkg

  ModuleNotFoundError: No module named 'apt_pkg'

  

  Original exception was:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig'

Call Stack (most recent call first):
  third/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  third/pybind11/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/home/alex/soft/graphics/vgc/vgc-2019-08-25/build/CMakeFiles/CMakeOutput.log".

```

**Comment by dalboris** [comment]
Great, thanks, this is very useful :)

There is indeed a conflict between python 3.6 and 3.7 which are both installed on your distrib. CMake chooses Python 3.6, but unfortunately, in your `/usr/lib/python3/dist-packages`, there are only the libraries for Python 3.7. When CMake runs, it calls the program `/usr/bin/python3.6` for doing some configuration, and `/usr/bin/python3.6` is looking for the file `apt_pkg.cpython-36m-x86_64-linux-gnu.so` which it cannot find. Only the file `apt_pkg.cpython-37m-x86_64-linux-gnu.so` is present.

I think the simpler fix in your case is tell CMake to use Python 3.7 instead of Python 3.6:

```
cd vgc
rm -rf build
mkdir build
cmake .. -DPYTHON_EXECUTABLE="/usr/bin/python3.7"
```

The more long-term fix is to fix your Python installation so that both the `36m` and `37m` versions of the python libraries are in `/usr/lib/python3/dist-packages`, so that you can also compile using Python 3.6 if you which. I'm not exactly sure the best way to do this without doing more research.

By the way, you can delete the symlink I just had you created earlier, since it points to a file that doesn't exist anyway:

```
rm /usr/lib/python3/dist-packages/apt_pkg.so
```

**Comment by prokoudine** [comment]
Builds and launches, thanks a lot :)

**Comment by dalboris** [comment]
Great :)

For future reference, I just made a few tests on a fresh Ubuntu 19.04 on VirtualBox, and the following was the minimal working set of commands to compile and launch VGC:

```
sudo apt install git cmake python3-dev qtbase5-dev
git clone git clone https://github.com/vgc/vgc.git
mkdir build-vgc
cd build-vgc
cmake ../vgc
make
```

![Screenshot from 2019-08-25 15-53-21](https://user-images.githubusercontent.com/4809739/63651041-6eff1500-c751-11e9-9290-15f2b874dbe2.png)

Note 1: I didn't have pressure sensitivity from my Wacom tablet, but I assume this is due to VirtualBox. @prokoudine: Do you have a Wacom tablet and have pressure sensitivity work? Stroke width should depend on pressure. If it works the effect is obvious. If you're not sure it means it doesn't work.

Note 2: The VGC icon on the taskbar and top bar was super ugly/pixelated. I'm not sure if this is due to VirtualBox or Gnome: it looks good on non-virtualized Kubuntu 18.04. @prokoudine: Is it looking pixelated for you too?

**Comment by dalboris** [comment]
Here is on Kubuntu 18.04 with pressure sensitivity working:

![image](https://user-images.githubusercontent.com/4809739/63651211-a3270580-c752-11e9-8e2c-0e3ce5b5da78.png)
