### ISSUE TITLE
Compile error: member access into incomplete type 'PyFrameObject'

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#1074]
We get the following compile error when trying to compile with Python 3.11:

```
error: member access into incomplete type 'PyFrameObject'
```

This is caused by a C API change in Python 3.11. Upgrading to the latest version of pybind11 should fix the problem.

**Comment by dalboris** [comment]
Note: we're currently using pybind v2.9.1. Work in pybind11 to support Python 3.11 was progressively done starting at v2.8.1 (see https://github.com/pybind/pybind11/releases, search for "3.11"), with 2.10.0 indicating "Initial support added for Python 3.11".

**Comment by dalboris** [comment]
How to test on Kubuntu 22.04:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.11 python3.11-dev
git clone --recurse-submodules https://github.com/vgc/vgc.git
cd vgc && mkdir build && cd build
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DQt5_DIR="~/Qt/5.15.2/gcc_64/lib/cmake/Qt5" \
    -DPython_EXECUTABLE=/usr/bin/python3.11
cmake --build . --parallel 8
```

Current errors / warnings:

```
/home/boris/vgc-python311/third/pybind11/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
/home/boris/vgc-python311/third/pybind11/include/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}

/home/boris/vgc-python311/libs/vgc/core/python.cpp: In constructor ‘vgc::core::PythonInterpreter::ScopedInterpreter_::ScopedInterpreter_(const string&, const string&)’:
/home/boris/vgc-python311/libs/vgc/core/python.cpp:49:26: warning: ‘void Py_SetProgramName(const wchar_t*)’ is deprecated [-Wdeprecated-declarations]

/home/boris/vgc-python311/libs/vgc/core/python.cpp:71:25: warning: ‘void Py_SetPythonHome(const wchar_t*)’ is deprecated [-Wdeprecated-declarations]

/home/boris/vgc-python311/libs/vgc/core/python.cpp:130:24: warning: ‘void PySys_SetArgvEx(int, wchar_t**, int)’ is deprecated [-Wdeprecated-declarations]
```
